### ISSUE TITLE
Design decisions

### ISSUE THREAD

**Issue by jthomasmock** [leesharpe/nflseedR#9] opened 2021-02-18 01:31 UTC
I think that it may be worth considering splitting out the `simulate_nfl()` functions from the subsequent functions that create the `teams`, `team_wins`, `overall`, summarizations. 

In this situation, `simulate_nfl()` would only output the `games` object which could then be put into the other calculations.

This would help with troubleshooting as most mistakes will be made with custom functions that output the games object, and if the `games` object is malformed it could be addressed there rather than it getting lost in the intermediate steps.

**Comment by jthomasmock** [comment] 2021-02-18 01:48
This is primarily aimed at the useful error message that I can't seem to do anything about... 😢 

Edit: ((This is once again because I didn't do `week != w` which I just realized. 😭 ))

```
Error in compute_draft_order(., games = games, h2h = h2h_df, tiebreaker_depth = tiebreaker_depth,  :                
  Something went wrong and the function has entered an infinite loop. Does the number of postseason games match the number of playoff seeds?
```

The parts I can control as a user stop before the embedded calc for playoffs.

**Comment by jthomasmock** [comment] 2021-02-18 01:55
This approach may also be helpful if we could keep some of the intermediate columns that help us get to or "explain" our simulation results, but maybe that's not intended here?

**Comment by leesharpe** [comment] 2021-02-18 03:24
The infinite loop error is caused by an inconsistency between the playoff teams and the playoff games, wherein it can't correctly determine what the games the next playoff opponents should be.

I will tonight add error checking for the week != w error, if @mrcaseb hasn't already. That one is very easy to catch. I'm trying to think about whether the correct thing to do is:
1) Ignore the user's changes to other games, if they make them.
2) Error out that the user's function did it wrong.

Thoughts?

**Comment by leesharpe** [comment] 2021-02-18 07:22
OK, I took what @mrcaseb did and added a CRAPLOAD of additional error-checking with (hopefully) helpful messages.

**Comment by leesharpe** [comment] 2021-02-19 05:38
Decided on the second approach, closing this issue.

**Closed by leesharpe** 2021-02-19 05:38 UTC
